apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: forecaster-workloads

resources:
  - namespace.yaml
  - resource_quotas.yaml
  - ../monitoring/dqn_prometheus_rules.yaml

commonLabels:
  app.kubernetes.io/name: dqn-advisor
  app.kubernetes.io/part-of: fintech-forex
  app.kubernetes.io/managed-by: fluxcd
