
FROM 731833471586.dkr.ecr.ap-southeast-1.amazonaws.com/forecaster/base:latest

LABEL component="serving"
LABEL description="KServe custom predictor serving Gaussian mu/sigma predictions"

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY probabilisticforecaster/ /app/probabilisticforecaster/

COPY probabilisticforecaster/kubeflow/serving/predictor.py /app/predictor.py


ENTRYPOINT ["python", "predictor.py"]
