---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fintech-forex-dqnpf
  namespace: flux-system
spec:
  interval: 1m
  url: http://gitea-http.gitea.svc.cluster.local:3000/Fintech/forex.git
  ref:
    branch: master
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dqnpf-intraday
  namespace: flux-system
spec:
  interval: 1m
  path: ./tradingmodel/intraday/dqnpf/kubeflow/manifests
  sourceRef:
    kind: GitRepository
    name: fintech-forex-dqnpf
  prune: true
  wait: true
  timeout: 10m
