apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: peterbean

resources:
  - inferenceservice.yaml
  - prometheus-rules.yaml

commonLabels:
  app.kubernetes.io/name: dqnpf-intraday
  app.kubernetes.io/part-of: fintech-forex
  app.kubernetes.io/managed-by: fluxcd
