"""Training entry point for the DQN trading agent.

Wires together configuration, device resolution, agent, environment client,
checkpoint manager, and state preprocessor. Runs the training loop with
configurable episodes, steps, gradient updates, target syncs, and checkpointing.

Supports two modes:

- **Fixed timestamps**: episode_start_ts / episode_end_ts (legacy, all episodes
  train on the same time window).
- **Date-range**: date_start / date_end / hour_of_day_start / hour_of_day_end
  (one episode per calendar date, each with its own time window).

Usage:
    python -m deepqnetwork.train --config deepqnetwork/config.yaml
    python -m deepqnetwork.train --config deepqnetwork/config.yaml --checkpoint path/to/checkpoint.pt
"""

from __future__ import annotations

import logging
import time
from dataclasses import asdict
from typing import Iterator

from deepqnetwork.agent import DQNAgent
from deepqnetwork.checkpoint_manager import CheckpointManager
from deepqnetwork.config import DQNConfig, load_config
from deepqnetwork.episode_windows import iter_date_episodes
from deepqnetwork.environment_client import EnvironmentClient
from deepqnetwork.preprocessor import StatePreprocessor
from deepqnetwork.utils import generate_order_id, resolve_device, setup_logging

logger = logging.getLogger(__name__)


def _restore_checkpoint(
    checkpoint_data: dict,
    agent: DQNAgent,
) -> int:
    """Restore agent state from a checkpoint dictionary.

    Args:
        checkpoint_data: Dictionary loaded from a checkpoint file.
        agent: The DQNAgent instance to restore state into.

    Returns:
        The episode count to resume from.
    """
    if not checkpoint_data:
        return 0

    # Restore network weights
    agent.q_network.load_state_dict(checkpoint_data["q_network_state_dict"])
    agent.target_network.load_state_dict(checkpoint_data["target_network_state_dict"])
    agent.optimizer.load_state_dict(checkpoint_data["optimizer_state_dict"])

    # Restore training state
    agent.epsilon = checkpoint_data["epsilon"]
    agent.step_count = checkpoint_data["step_count"]
    start_episode = checkpoint_data.get("episode_count", 0)

    logger.info(
        "Resumed from checkpoint: episode=%d, step_count=%d, epsilon=%.4f",
        start_episode,
        agent.step_count,
        agent.epsilon,
    )
    return start_episode


# Per-date episode windows are generated by the shared helper so DQN training
# and the DQNPF backtest slice dates identically (train/eval parity). The alias
# preserves the historical name used at the call site and in the spec chain.
_iter_date_episodes = iter_date_episodes


def train(config: DQNConfig) -> None:
    """Run the DQN training loop.

    Args:
        config: Fully resolved DQN configuration.
    """
    # Ensure logs are visible even when train() is called directly (e.g. from
    # the Kubeflow dqn_training component) instead of via main(). Without a
    # configured handler the root logger drops every INFO record (including the
    # episode and [progress] lines) so only the modelenv subprocess output
    # shows. setup_logging() is idempotent, so this no-ops when main() already
    # configured logging.
    if not logging.getLogger().handlers:
        setup_logging(level="INFO", csv_path=f"{config.checkpoint_dir}/training.log")

    # Resolve device
    device = resolve_device(config.device)
    logger.info("Device selected: %s", device)

    # Log full resolved config
    logger.info("Resolved configuration: %s", asdict(config))

    # Create state preprocessor
    preprocessor = StatePreprocessor(device)

    # Create DQN agent
    agent = DQNAgent(config, device)

    # Create environment client
    env_client = EnvironmentClient(
        address=config.grpc_address,
        timeout=30.0,
        max_retries=5,
    )

    # Create checkpoint manager
    checkpoint_mgr = CheckpointManager(
        checkpoint_dir=config.checkpoint_dir,
        s3_prefix=config.s3_checkpoint_prefix,
        symbol=config.symbol,
        horizon=str(config.step_size_seconds),
        version=config.model_version or "1",
    )

    # Optional resume from checkpoint
    start_episode = 0
    if config.checkpoint:
        checkpoint_data = checkpoint_mgr.load(config.checkpoint)
        start_episode = _restore_checkpoint(checkpoint_data, agent)

    # Training loop
    step_count = agent.step_count
    recent_rewards: list[float] = []
    best_reward = float("-inf")

    # Resolve episode windows: date-range mode takes precedence over fixed
    # episode_start_ts/end_ts.
    if config.date_start and config.date_end:
        episode_windows = _iter_date_episodes(
            config.date_start,
            config.date_end,
            config.hour_of_day_start,
            config.hour_of_day_end,
        )
        mode = "date-range"
    else:
        # Legacy fixed-timestamp mode, same window for every episode.
        episode_windows = [
            (config.episode_start_ts, config.episode_end_ts)
        ] * config.num_episodes_per_range
        mode = "fixed"

    logger.info(
        "Starting training: episodes=%d (mode=%s), max_steps=%d, "
        "train_freq=%d, target_update_freq=%d",
        len(episode_windows),
        mode,
        config.max_steps_per_episode,
        config.train_freq,
        config.target_update_freq,
    )

    repeats_per_date = config.repeats_per_date if mode == "date-range" else 1
    overall_episode = start_episode
    total_episodes = len(episode_windows) * repeats_per_date

    if mode == "date-range":
        # Episode count is driven by the date range and repeats_per_date, not
        # num_episodes_per_range (which only governs fixed-window mode). Log the
        # actual total so the ignored knob doesn't mislead.
        logger.info(
            "date-range mode: %d date windows x %d repeats_per_date = %d episodes "
            "(num_episodes_per_range=%d is ignored in this mode)",
            len(episode_windows),
            repeats_per_date,
            total_episodes,
            config.num_episodes_per_range,
        )

    # Anneal epsilon over the whole run, not a fixed prefix. When
    # epsilon_decay_steps is left unset (<= 0), derive it from the total step
    # budget so exploration tapers across roughly all episodes instead of
    # collapsing to epsilon_end in the first few. Each episode terminates at its
    # session end, so estimate per-episode steps from the window length (capped
    # by max_steps_per_episode); fall back to the cap for fixed-window mode.
    if config.epsilon_decay_steps <= 0:
        budget = 0
        for ep_start, ep_end in episode_windows:
            window_steps = (ep_end - ep_start) // config.step_size_seconds
            per_episode = (
                config.max_steps_per_episode
                if window_steps <= 0
                else min(config.max_steps_per_episode, window_steps)
            )
            budget += per_episode
        config.epsilon_decay_steps = max(1, budget * repeats_per_date)
        logger.info(
            "epsilon_decay_steps auto-derived from step budget: %d "
            "(total_episodes=%d, ~%d steps/episode)",
            config.epsilon_decay_steps,
            total_episodes,
            config.epsilon_decay_steps // max(1, total_episodes),
        )

    for date_idx, (ep_start, ep_end) in enumerate(episode_windows):
        for repeat in range(repeats_per_date):
            if overall_episode < start_episode:
                overall_episode += 1
                continue
            episode_start_time = time.time()

            # Reset environment for new episode
            obs = env_client.reset(
                symbol=config.symbol,
                episode_start_ts=ep_start,
                episode_end_ts=ep_end,
                step_size_seconds=config.step_size_seconds,
            )
            state = preprocessor.process(obs)
            episode_reward = 0.0
            episode_losses: list[float] = []
            last_loss: float | None = None

            for step in range(config.max_steps_per_episode):
                # Select action (epsilon-greedy)
                action = agent.select_action(state, training=True)

                # Step environment
                response = env_client.step(action, generate_order_id())
                next_state = preprocessor.process(response.data)
                reward = response.data.reward
                done = response.data.done

                # Store transition in replay buffer (numpy arrays)
                state_np = state.cpu().numpy()
                next_state_np = next_state.cpu().numpy()
                agent.replay_buffer.push(state_np, action, reward, next_state_np, done)

                # Gradient update at train_freq intervals
                loss = None
                if (
                    len(agent.replay_buffer) >= config.batch_size
                    and step_count % config.train_freq == 0
                ):
                    loss = agent.update()
                    if loss is not None:
                        episode_losses.append(loss)
                        last_loss = loss

                # Epsilon decay
                agent.step_epsilon()

                # Target network sync at target_update_freq intervals
                step_count += 1
                if step_count % config.target_update_freq == 0:
                    agent.sync_target()

                # Advance state
                state = next_state
                episode_reward += reward

                # Intra-episode progress logging. Episodes can be tens of
                # thousands of gRPC steps, so without this nothing is logged
                # between the episode-start and episode-end lines.
                if (
                    config.progress_log_interval
                    and step > 0
                    and step % config.progress_log_interval == 0
                ):
                    elapsed = time.time() - episode_start_time
                    steps_per_sec = step / elapsed if elapsed > 0 else 0.0
                    logger.info(
                        "  [progress] ep=%d step=%d/%d global_step=%d epsilon=%.3f "
                        "buffer=%d reward=%.4f last_loss=%s %.1f steps/s",
                        overall_episode,
                        step,
                        config.max_steps_per_episode,
                        step_count,
                        agent.epsilon,
                        len(agent.replay_buffer),
                        episode_reward,
                        f"{last_loss:.6f}" if last_loss is not None else "n/a",
                        steps_per_sec,
                    )

                if done:
                    break

            # Episode complete, logging
            episode_duration = time.time() - episode_start_time
            avg_loss = (
                sum(episode_losses) / len(episode_losses) if episode_losses else 0.0
            )
            episode_length = step + 1

            # Track rewards for rolling average
            recent_rewards.append(episode_reward)
            if len(recent_rewards) > 100:
                recent_rewards.pop(0)
            best_reward = max(best_reward, episode_reward)

            # Log episode metrics
            if overall_episode % config.log_interval == 0:
                avg_recent = sum(recent_rewards) / len(recent_rewards)
                logger.info(
                    "Episode %d | date=%s | repeat=%d | reward=%.4f | length=%d | "
                    "avg_loss=%.6f | epsilon=%.4f | duration=%.1fs | "
                    "avg_100=%.4f | best=%.4f",
                    overall_episode,
                    ep_start,
                    repeat,
                    episode_reward,
                    episode_length,
                    avg_loss,
                    agent.epsilon,
                    episode_duration,
                    avg_recent,
                    best_reward,
                )

            # Checkpoint saving at configurable intervals
            if overall_episode > 0 and overall_episode % config.checkpoint_interval == 0:
                avg_recent = sum(recent_rewards) / len(recent_rewards)
                logger.info(
                    "Checkpoint interval: best_reward=%.4f, avg_100=%.4f",
                    best_reward,
                    avg_recent,
                )
                checkpoint_mgr.save(
                    episode=overall_episode,
                    q_network=agent.q_network,
                    target_network=agent.target_network,
                    optimizer=agent.optimizer,
                    epsilon=agent.epsilon,
                    step_count=step_count,
                    config=asdict(config),
                )

            overall_episode += 1

    # Final checkpoint at end of training
    logger.info("Training complete. Saving final checkpoint.")
    checkpoint_mgr.save(
        episode=overall_episode,
        q_network=agent.q_network,
        target_network=agent.target_network,
        optimizer=agent.optimizer,
        epsilon=agent.epsilon,
        step_count=step_count,
        config=asdict(config),
    )

    # Clean up
    env_client.close()
    logger.info(
        "Training finished: %d episodes, %d total steps, best_reward=%.4f",
        overall_episode - start_episode,
        step_count,
        best_reward,
    )


def main() -> None:
    """CLI entry point for DQN training."""
    config = load_config()

    # Setup logging
    setup_logging(level="INFO", csv_path=f"{config.checkpoint_dir}/training.log")

    # Log startup
    logger.info("DQN Training Agent starting...")
    logger.info("Mode: %s", config.mode)

    if config.mode != "train":
        logger.error("train.py is the training entry point. Use mode='train'.")
        raise SystemExit(1)

    train(config)


if __name__ == "__main__":
    main()
